export const queryKeys = {
  config: ['config'] as const,
  stats: ['stats'] as const,
  faqs: ['faqs'] as const,
  testimonials: ['testimonials'] as const,
  teachers: ['teacher-moderators'] as const,
  boards: ['boards'] as const,
  years: ['years'] as const,
  hierarchyMetadata: ['hierarchy', 'metadata'] as const,
  banners: ['banners'] as const,
  notices: ['notices'] as const,
  notes: ['notes'] as const,
  notice: (id: string) => ['notices', id] as const,
  classes: ['classes'] as const,
  subjects: (classSlug: string) => ['subjects', classSlug] as const,
  chapters: (subjectSlug: string) => ['chapters', subjectSlug] as const,
  lectures: (chapterId?: string) => ['lectures', chapterId] as const,
  mcq: (chapterId?: string) => ['mcq', chapterId] as const,
  cq: (chapterId?: string) => ['cq', chapterId] as const,
  lecture: (id: string) => ['lecture', id] as const,
  cqDetail: (id: string) => ['cq', 'detail', id] as const,
  search: (query: string) => ['search', query] as const,
  payment: {
    check: (contentType: string, contentId: string) => ['payment', 'check', contentType, contentId] as const,
    batchCheck: (items: unknown) => ['payment', 'batch-check', items] as const,
    history: () => ['payment', 'history'] as const,
    accounts: () => ['payment', 'accounts'] as const,
  },
  featuredCourses: ['courses', 'featured'] as const,
  boardQuestionFilters: ['board-questions', 'filters'] as const,
  boardQuestions: (params?: Record<string, unknown>) => ['board-questions', params] as const,
  premiumPrices: ['premium', 'prices'] as const,
  blog: {
    list: (params?: Record<string, unknown>) => ['blog', 'list', params] as const,
    detail: (slug: string) => ['blog', 'detail', slug] as const,
    categories: () => ['blog', 'categories'] as const,
    tags: () => ['blog', 'tags'] as const,
    admin: {
      list: (params?: Record<string, unknown>) => ['admin', 'blog', 'list', params] as const,
      detail: (id: string) => ['admin', 'blog', 'detail', id] as const,
      categories: () => ['admin', 'blog', 'categories'] as const,
      tags: () => ['admin', 'blog', 'tags'] as const,
    },
  },
  suggestions: (params?: Record<string, unknown>) => ['suggestions', params] as const,
  suggestion: (id: string) => ['suggestion', id] as const,
  packages: () => ['packages'] as const,
  bundles: (params?: Record<string, unknown>) => ['bundles', params] as const,
  admin: {
    stats: () => ['admin', 'stats'] as const,
    users: (params?: Record<string, unknown>) => ['admin', 'users', params] as const,
    feedback: (params?: Record<string, unknown>) => ['admin', 'feedback', params] as const,
    feedbackMessages: (id: string) => ['admin', 'feedback', id, 'messages'] as const,
    suggestions: (params?: Record<string, unknown>) => ['admin', 'suggestions', params] as const,
    teacherModerators: (params?: Record<string, unknown>) => ['admin', 'teacher-moderators', params] as const,
    notifications: (params?: Record<string, unknown>) => ['admin', 'notifications', params] as const,
    permissions: () => ['admin', 'permissions'] as const,
    navigation: () => ['admin', 'navigation'] as const,
    settings: () => ['admin', 'settings'] as const,
    database: () => ['admin', 'database'] as const,
    packages: (params?: Record<string, unknown>) => ['admin', 'packages', params] as const,
    packageDetail: (id: string) => ['admin', 'packages', id] as const,
    featured: (params?: Record<string, unknown>) => ['admin', 'featured', params] as const,
    contentTypes: () => ['admin', 'content-types'] as const,
    payments: (params?: Record<string, unknown>) => ['admin', 'payments', params] as const,
    subscriptions: (params?: Record<string, unknown>) => ['admin', 'subscriptions', params] as const,
    contentPurchases: (params?: Record<string, unknown>) => ['admin', 'content-purchases', params] as const,
    mcqExamPurchases: (params?: Record<string, unknown>) => ['admin', 'mcq-exam-purchases', params] as const,
    mcq: (params?: Record<string, unknown>) => ['admin', 'mcq', params] as const,
    cq: (params?: Record<string, unknown>) => ['admin', 'cq', params] as const,
    lectures: (params?: Record<string, unknown>) => ['admin', 'lectures', params] as const,
    exams: (params?: Record<string, unknown>) => ['admin', 'exams', params] as const,
    examQuestions: (params?: Record<string, unknown>) => ['admin', 'exams', 'questions', params] as const,
    examResults: (params?: Record<string, unknown>) => ['admin', 'exam-results', params] as const,
    knowledgeQuestions: (params?: Record<string, unknown>) => ['admin', 'knowledge-questions', params] as const,
    boardQuestions: (params?: Record<string, unknown>) => ['admin', 'board-questions', params] as const,
    adminClasses: () => ['admin', 'classes'] as const,
    adminSubjects: (classId?: string) => ['admin', 'subjects', classId ?? 'all'] as const,
    adminChapters: (subjectId?: string) => ['admin', 'chapters', subjectId ?? 'all'] as const,
    workflowAnalytics: (params?: Record<string, unknown>) => ['admin', 'workflow', 'analytics', params] as const,
  },
  examPackages: {
    mcq: (params?: Record<string, unknown>) => ['mcq-exam-packages', params] as const,
    cq: (params?: Record<string, unknown>) => ['cq-exam-packages', params] as const,
  },
  courses: (params?: Record<string, unknown>) =>
    ['courses', params] as const,
  courseDetail: (slug: string) =>
    ['course', slug] as const,
  coursePurchases: () =>
    ['course-purchases'] as const,
  analytics: {
    revenue: (params?: Record<string, unknown>) => ['analytics', 'revenue', params] as const,
    students: (params?: Record<string, unknown>) => ['analytics', 'students', params] as const,
    retention: (params?: Record<string, unknown>) => ['analytics', 'retention', params] as const,
    conversion: (params?: Record<string, unknown>) => ['analytics', 'conversion', params] as const,
    dropoff: (params?: Record<string, unknown>) => ['analytics', 'dropoff', params] as const,
    courses: (params?: Record<string, unknown>) => ['analytics', 'courses', params] as const,
    lectures: (params?: Record<string, unknown>) => ['analytics', 'lectures', params] as const,
    mcq: (params?: Record<string, unknown>) => ['analytics', 'mcq', params] as const,
    cq: (params?: Record<string, unknown>) => ['analytics', 'cq', params] as const,
    payments: (params?: Record<string, unknown>) => ['analytics', 'payments', params] as const,
    acquisition: (params?: Record<string, unknown>) => ['analytics', 'acquisition', params] as const,
    search: (params?: Record<string, unknown>) => ['analytics', 'search', params] as const,
    devices: (params?: Record<string, unknown>) => ['analytics', 'devices', params] as const,
    geo: (params?: Record<string, unknown>) => ['analytics', 'geo', params] as const,
    realtime: () => ['analytics', 'realtime'] as const,
    insights: (params?: Record<string, unknown>) => ['analytics', 'insights', params] as const,
    predictions: (params?: Record<string, unknown>) => ['analytics', 'predictions', params] as const,
    alerts: () => ['analytics', 'alerts'] as const,
    reports: () => ['analytics', 'reports'] as const,
  },
  notifications: {
    list: (params?: Record<string, unknown>) => ['student', 'notifications', params] as const,
    unreadCount: () => ['student', 'notifications', 'unread'] as const,
  },
  student: {
    learningDashboard: () => ['student', 'learning-dashboard'] as const,
    recommendations: () => ['student', 'recommendations'] as const,
    weaknesses: () => ['student', 'weaknesses'] as const,
    revision: () => ['student', 'revision'] as const,
    analytics: (params?: Record<string, unknown>) => ['student', 'analytics', params] as const,
    calendar: (year: number, month: number) => ['student', 'calendar', year, month] as const,
    achievements: () => ['student', 'achievements'] as const,
    achievement: (id: string) => ['student', 'achievements', id] as const,
    insights: (params?: Record<string, unknown>) => ['student', 'insights', params] as const,
    payments: () => ['student', 'payments'] as const,
    subscriptions: () => ['student', 'subscriptions'] as const,
  },
  dashboard: () => ['user', 'dashboard'] as const,
  recentLectures: () => ['user', 'recent-lectures'] as const,
  recentlyViewed: () => ['user', 'recently-viewed'] as const,
  personalizedContinueLearning: () => ['user', 'personalized-continue-learning'] as const,
}
